### ISSUE TITLE
Reentrancy attack allowed through drawing a loan

### ISSUE THREAD

**Issue by mrthankyou** [Anish-Agnihotri/pawnft#2]
## Description of Bug
The drawLoan function is designed such that a malicious actor can run a reentrancy attack when a NFT owner is sent a payment via `call`.

Imagine a NFT owner can construct a contract specifically designed to callback the drawLoan function when it receives a payment. If that malicious contract then creates a loan and waits for someone to make a bid for that loan, the malicious contract can then call `drawLoan` and retrieve capital from the loan. 

On line 259, the capital is sent to the malicious contract.

```
(bool sent, ) = payable(msg.sender).call{value: loan.loanAmount - loan.loanAmountDrawn}("");
```

It's only after the money is sent to the malicious contract is the `loanAmountDrawn` value changes via line 263:

```
loan.loanAmountDrawn = loan.loanAmount;
```

## Solution
`loanAmountDrawn` should be set before ETH is sent to the malicious actor. That way, the malicious contract will not be able to re-run the `drawLoan` contract since the `require` statement will fail on line 256:

```
require(loan.loanAmountDrawn < loan.loanAmount, "Max draw capacity reached.");
```

## Anything Else We Should Know
[Reentrancy attack article](https://medium.com/coinmonks/protect-your-solidity-smart-contracts-from-reentrancy-attacks-9972c3af7c21#:~:text=They%20are%20devastating%20for%20two,before%20it%20resolves%20any%20effects.)

**Comment by Anish-Agnihotri** [comment]
Great catch, thank you. 

Will implement the [checks-effects-interactions pattern](https://docs.soliditylang.org/en/v0.5.11/security-considerations.html#use-the-checks-effects-interactions-pattern) and move line 263 up.

**Comment by mrthankyou** [comment]
@Anish-Agnihotri 

Greatly appreciate getting a fix for this so fast. Also thank you for adding me to the readme. I appreciate that a lot.

**Comment by Anish-Agnihotri** [comment]
Of course, thank you very much for finding these bugs!
